server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh           # 路由的 ID，没有固定规则但要求唯一
          #uri: http://localhost:8001  # 匹配后蹄冻服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**     # 断言，路径相匹配的进行路由

        - id: payment_routh2           # 路由的 ID，没有固定规则但要求唯一
         # uri: http://localhost:8001  # 匹配后蹄冻服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**     # 断言，路径相匹配的进行路由
eureka:
  client:
    # 注册自己
    register-with-eureka: true
    # 检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
