server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  rabbitmq:
    host: 192.168.17.12
    port: 5672
    username: admin
    password: admin
  cloud:
    config:
      server:
        git:
          uri: git://github.com/zhangyu389/spring-cloud-config.git
          search-paths: spring-cloud-config
      label: main
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#暴露rabbitmq监控端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'