server:
  port: 80
eureka:
  client:
    # 不注册自己
    register-with-eureka: false
    # 表示自己是注册中心，不用检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-order-service
ribbon:
  # 建立连接后，在服务端读取数据的时间
  ReadTimeout: 5000
  # 建立连接所需的时间
  ConnetTimeout: 5000

logging:
  level:
    com.zy.springcloud.service.PaymentFeignService: debug



