server:
  port: 8001
spring:
  application:
    name: cloud-payment-hysreix-service
eureka:
  client:
    # 不注册自己
    register-with-eureka: true
    # 表示自己是注册中心，不用检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: paymenthystrix8001  #修改eureka显示的名字
    prefer-ip-address: true   #显示IP地址